name: Deploy

on:
    workflow_call:

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: clone the code
              uses:  actions/checkout@v7
            - name: Deploy via nginx
              run: cp main.html /var/www/html/index.html
            - name: Deploy the code
              run: echo "code deployed to AWS EC2"